Llvdl\Domino\Domain\Turn:
    type: entity
    table: turn
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        number:
            type: integer
        playerNumber:
            type: integer
