Llvdl\Domino\Domain\Player:
    type: entity
    table: player
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        number:
            type: integer

    manyToOne:
        game:
            targetEntity: Llvdl\Domino\Domain\Game
            inversedBy: players
            joinColumn:
                name: game_id
                referencedColumnName: id
    oneToMany:
        stones:
            targetEntity: Llvdl\Domino\Domain\Stone
            mappedBy: player
            cascade:
                - persist
