Llvdl\Domino\Domain\State:
    type: entity
    table: state
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 16
