Llvdl\Domino\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    oneToOne:
        state:
            targetEntity: Llvdl\Domino\State
            cascade:
                - persist
            joinColumn:
                name: state_id
                referencedColumnName: id
        currentTurn:
            targetEntity: Llvdl\Domino\Turn
            cascade:
                - persist
            joinColumn:
                name: turn_id
                referencedColumnName: id
    oneToMany:
        players:
            targetEntity: Llvdl\Domino\Player
            mappedBy: game
            cascade:
                - persist

