Llvdl\Domino\Stone:
    type: entity
    table: stone
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        topValue:
            type: integer
        bottomValue:
            type: integer
    manyToOne:
        player:
            targetEntity: Llvdl\Domino\Player
            inversedBy: stones
            joinColumn:
                name: player_id
                referencedColumnName: id
