services:
    app.game_overview_controller:
        class: AppBundle\Controller\GameOverviewController
        arguments:
            - "@templating"
            - "@router"
            - "@form.factory"
            - "@app.game_service"

    app.game_detail_controller:
        class: AppBundle\Controller\GameDetailController
        arguments:
            - "@templating"
            - "@router"
            - "@form.factory"
            - "@app.game_service"

    app.player_controller:
        class: AppBundle\Controller\PlayerController
        arguments:
            - "@templating"
            - "@router"
            - "@form.factory"
            - "@app.game_service"
